### ISSUE TITLE
Publishing Docker images is broken

### ISSUE THREAD

**Issue by alexellis** [alexellis/derek#129]
## Expected Behaviour

New Docker images to appear upon release tag

## Current Behaviour

<img width="1400" alt="Screenshot 2019-07-21 at 15 06 48" src="https://user-images.githubusercontent.com/6358735/61592294-39529380-abc9-11e9-9049-d62448d459bc.png">

## Possible Solution

Investigate and fix.

## Steps to Reproduce (for bugs)

1. Cut a release tag
2. See error above

**Comment by alexellis** [comment]
Find the full logs here -> https://travis-ci.org/alexellis/derek/builds/561697455

**Comment by alexellis** [comment]
`build.sh` -> https://github.com/alexellis/derek/blob/master/build.sh
`.travis.yml` -> https://github.com/alexellis/derek/blob/master/.travis.yml

I suspect that we are building to a different temporary tag, to the one which we are expecting when we re-tag and push that with the release name.

**Comment by matipan** [comment]
I think the problem might be that the `build.sh` is building the image using the name `alexellis/derek:latest-dev` but then in travis we are tagging/pushing using the following name: `$DOCKER_NS/derek:[latest-dev,$TRAVIS_TAG]. However the `$DOCKER_NS` is set to `openfaas` instead of `alexellis`, which was the original username used to build the image.

**Comment by affix** [comment]
@matipan Yeah I've made `build.sh` use the `$DOCKER_NS` variable
