### ISSUE TITLE
Suggestion: make this project more visible

### ISSUE THREAD

**Issue by sesam** [alexellis/derek#165]
As a user,
I want this project to be visible and easily comparable to other similar projects,
in order to find this project again next time, and to make it easier to get inflow of new ideas and users

## Context
I've been wanting something like homu for a while, which became bors-ng, but the whole solution seemed a bit too involved to be applicable to my current client. If, at that time, I would have imagined there are a lot of options, I would have ended up on the repo-automation-tools above and the toolkit for making your own. And we actually did make our own, but it's a deployed and heavy-handed kind of bot, which keeps being slow and throwing errors and making us retry. Doing deploys as a comment inside the relevant PR seems it would be a huge improvement. And now I'm trying to figure out if Derek is, or can soon enough be, a solution for our various needs.

**Comment by alexellis** [comment]
Hi @sesam thank you for your feedback. I'll close the issue since we use the tracker for bugs and features.

It's nice of you to want the project to be more visible. Feel free to make suggestions on how you see that happening. I'm listening. 

Blog posts and tweets from users can be helpful. 

Regarding your other request for deployments, that sounds like a separate request and feature.

Why don't you join the Slack community to have a conversation about your ideas with the other users? 

Alex

**Comment by alexellis** [comment]
From your recent activity on the repo and the various issues that you've raised, it seems like you may be evaluating Derek for use at work or for participation in a feature. 

If that's the case then I think more synchronous conversation on Slack with the other users would be the most efficient way to achieve that.

**Comment by alexellis** [comment]
slack.openfaas.io
