### ISSUE TITLE
[Proposal] Add feature to auto label issues when an associated PR is raised

### ISSUE THREAD

**Issue by rgee0** [alexellis/derek#45]
Add a new feature so that when a contributor opens a PR and refences an issue, or multiple issues a label is automatically applied to the issue(s).

This could help contributors filter out at the top level those issues which are currently in progress / being addressed.

**Comment by s8sg** [comment]
Really like the idea. An initial thought. An issue can either be addressed from a PR that closes it, otherwise just as a reference. If the PR uses any keyword that closes issue [close, fix, resolve etc], we may add a tag with `in-progress`, otherwise `addressed`. 

Another alternative way to Lebel a PR with `issue-no` for any issues that are referred. In that way on the `PR section,` we can easily sort PR that refers to the same issue.
