### ISSUE TITLE
Suggestion: Allow any prefix such as "/" or another name as Derek trigger

### ISSUE THREAD

**Issue by alexellis** [alexellis/derek#63]
A PR was raised to enable users to invoke Derek via another prefix such as `"/"` in #56, but the code was not signed-off and the patch could not be merged.

This is a suggestion for third-party usage of Derek outside of the OpenFaaS project. I think this is a good beginner issue.

**Comment by neolit123** [comment]
me and @mrtind are collaborating on this change.

**Comment by alexellis** [comment]
Great :+1: I would expect this to be configured via environmental variable rather than DEREK.yml. That means that as an end user you would opt into this change when deploying.

Question - should Derek respond to the `/` alias by default? Cc @rgee0

**Comment by rgee0** [comment]
My initial thought was yes to the `/` question, but I started to think about orgs that employ multiple bots and how this could potentially lead to conflicts.  I think if we were to make `/` an alias then it also needs to be managed by an environmental variable, e.g. `slash-alias=true/false`

**Comment by neolit123** [comment]
if there are multiple bots on the same systems, ENV variables are a bad idea.
a local bot config per instance is the way to go (not the repo config).

BTW, @alexellis since this wasn't outlined in the first message in this issue me and @mrtind just went and added the option in the DEREK.yaml yesterday.

i see a discussion starting in here, so i'm going to hold on the collaboration with @mrtind, because we need a clear path for beginner issues. these even need a small tutorial explaining to new contributors how to make the requested change...

**Comment by alexellis** [comment]
So it's always good to ask when information is lacking or to check assumptions - that's part of the reason we are using proposal issues. I was expecting a similar implementation to the one submitted in the referenced PR which would use an env-var per deployment of the Derek container. That means all users of the hosted service use the name that references back to the project and brand of Derek.

People running their own bot can customise. 

That was my thinking.

**Comment by rgee0** [comment]
Also I was thinking more along the lines of multiple bots per org - like moby/moby who employ Poule and Derek. Others may do similar and their other bot trigger may be `/` hence it would need to be configurable.  I'd need to understand more about why env-vars are a bad idea.

**Comment by rgee0** [comment]
Derek close: implemented in #71
